POST http://localhost:4000/db/sign-up
Content-Type: application/json


{
    "name": "Tim",
    "email": "Tim@gmial.com",
    "password": "Timmy"
}

##

POST http://localhost:4000/db/login
Content-Type: application/json

{
    "email": "Tim@gmial.com", 
    "password": "Timmy"
}